apiVersion: backstage.io/v1beta2
kind: Location
metadata:
  name: example-systems
  description: A collection of all Backstage example systems
spec:
  targets:
    - ./systems/artist-engagement-portal-system.yaml
    - ./systems/audio-playback-system.yaml
    - ./systems/podcast-system.yaml
